/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example.todo.utilities

import org.example.todo.domain.LinkedList

class StringUtils {
    companion object {
        fun join(source: LinkedList): String {
            return JoinUtils.join(source)
        }

        fun split(source: String): LinkedList {
            return SplitUtils.split(source)
        }
    }
}
